### ISSUE TITLE
Some course titles not displaying correctly

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#25]
![screen shot 2015-03-05 at 10 23 30 pm](https://cloud.githubusercontent.com/assets/4276638/6519718/5d9f939e-c386-11e4-8eb3-2e11aaf06a8a.png)

**Comment by ajm188** [comment]
This has to do with some courses having title=nil. Should we add code to handle this, or should we not care and assume that we'll fix up the database?

**Comment by Aaronneyer** [comment]
So for the search results page, I think this is soon going to turn into more of a course instance search page, so will only show courses offered in a specific semester. If you're looking for just a general course, that's what the autcompletion course select field is for. So this will solve the problems of course titles in the search results.

However, these results will still show up in the autocompletion, just with a blank title, which is fine, but it leaves us with the problem that if people select the course, it gives them errors. I'll submit a PR soon that fixes this and displays some generic message like "This course appears to not have any actual course offerings, sorry about that". However, once we populate old courses via the SIS scraper, this will probably be a very unlikely occurrence.

**Comment by ajm188** [comment]
Temporarily patches #84

**Comment by matthewbentley** [comment]
I think this is the same bug: clicking a course titled "Title not found" results in a 500 error.  Ex: http://advise.case.edu/courses/EECS304

**Comment by ajm188** [comment]
This is actually related to the pull request we just merged in. I'll write a fix right now.

Where are we on getting the historical data in the database so that we don't need to care about this anymore?

**Comment by ajm188** [comment]
I'm not seeing this happening anymore. Feel free to re-open this issue if it happens again.

**Comment by JKobyP** [comment]
Is this the issue for courses displaying "Title not found"? Or is there a separate issue for that? Cause that's still happening.

**Comment by ajm188** [comment]
This is the one. Can you attach a screenshot or at least the offending course ID?

**Comment by ajm188** [comment]
If you want to try to tackle this, feel free.

**Comment by StephHippo** [comment]
I know what this is and it is dependent on getting the historical data in which I need to fix the SIS Downloader first. We still need code to upload those files after we have them but that should be the easiest part of all

**Comment by JKobyP** [comment]
Your screenshot:
![scrot](https://cloud.githubusercontent.com/assets/6590268/9449752/b7a2070a-4a72-11e5-93a9-3eb17fd329f3.png)

Let me know if I can help with this

**Comment by ajm188** [comment]
This appears to be more of a one-time infrastructure-y thing we need to do on our end, so I don't think there's much you would be able to help with, but I will definitely let you know.
